"""Scan the artifacts each chapter is expected to produce and write an index.

Run after executing the chapters:

    python scripts/use_tf2_env.py teaching/gen_chapter_figures.py

It does not retrain anything — it just scans the project for the artifacts
each chapter claims to produce (figures and exported models), and writes a
small `figures_index.md` so the teaching material can link to them directly.
"""

from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC = PROJECT_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from tf2tutorial.config import FIGURES_DIR  # noqa: E402

EXPECTED: dict[str, list[str]] = {
    "00_ml_basics": [
        "figures/chapter00_ml_vs_traditional.png",
        "figures/chapter00_supervised_learning.png",
        "figures/chapter00_train_val_test.png",
        "figures/chapter00_loss_function.png",
        "figures/chapter00_gradient_descent.png",
    ],
    "01_tensors_autograd": ["figures/chapter01_loss_surface.png"],
    "02_linear_regression": ["figures/chapter02_loss.png"],
    "03_mlp_mnist": ["figures/chapter03_history.png"],
    "04_cnn_cifar10": ["figures/chapter04_history.png", "figures/chapter04_confusion_matrix.png"],
    "05_text_imdb": ["figures/chapter05_history.png"],
    "06_transfer_learning": ["figures/chapter06_history.png", "figures/chapter06_finetune_history.png"],
    "07_callbacks_tensorboard": ["figures/chapter07_history.png"],
    "08_save_and_export": [
        "models/chapter08_mnist_mlp.keras",
        "models/chapter08_mnist_mlp.tflite",
        "models/saved/chapter08_mnist_mlp/saved_model.pb",
    ],
    "09_capstone_image_classifier": [
        "figures/chapter09_sample_images.png",
        "figures/chapter09_augmentation_demo.png",
        "figures/chapter09_history_phase1.png",
        "figures/chapter09_history_phase2.png",
        "figures/chapter09_confusion_matrix.png",
        "figures/chapter09_wrong_predictions.png",
        "figures/chapter09_model.tflite",
    ],
    "10_edge_raspberry_pi": [
        "figures/chapter10_benchmark.png",
        "models/chapter10_mobilenet_float32.tflite",
        "models/chapter10_mobilenet_float16.tflite",
        "models/chapter10_mobilenet_int8.tflite",
    ],
    "11_tfdata_pipeline": ["figures/chapter11_throughput.png"],
    "12_rnn_timeseries": ["figures/chapter12_history.png", "figures/chapter12_forecast.png"],
    "13_attention_transformer": [
        "figures/chapter13_history.png",
        "figures/chapter13_attention_heatmap.png",
    ],
    "14_autoencoder_gan": [
        "figures/chapter14_ae_reconstructions.png",
        "figures/chapter14_ae_interpolation.png",
        "figures/chapter14_gan_samples.png",
        "figures/chapter14_gan_losses.png",
    ],
    "15_custom_training": [
        "figures/chapter15_robustness.png",
        "figures/chapter15_eager_vs_graph.png",
    ],
    "16_text_capstone": [
        "figures/chapter16_history.png",
        "figures/chapter16_confusion.png",
    ],
}


def main() -> int:
    rows: list[str] = []
    rows.append("# Figures index\n")
    rows.append("Generated by `teaching/gen_chapter_figures.py`.\n")
    rows.append("| chapter | artifact (project-relative) | present |")
    rows.append("| --- | --- | --- |")
    for chap, files in EXPECTED.items():
        for rel in files:
            path = PROJECT_ROOT / rel
            ok = "[x]" if path.exists() else "[ ]"
            rows.append(f"| {chap} | `{rel}` | {ok} |")

    out_md = FIGURES_DIR / "figures_index.md"
    out_md.write_text("\n".join(rows) + "\n", encoding="utf-8")
    print(f"wrote {out_md}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
